### ISSUE TITLE
Recipe Cloning/relating 

### ISSUE THREAD

**Issue by jelloeggy** [gthole/drink-stash#12]
Suggestion based on recent used (and seeing your comments on 370 Comm Ave):
Create a "clone recipe" feature that allows people to duplicate, make the changes, and create a new name. Because it would be duplicated off an existing recipe, if that parentage/breadcrump is tracked somehow you basically start to build a network of variations that could lead to other features (i.e. a sidebar link that shows what it was cloned from, or shows what a base recipe has been cloned to, ways to make suggestions)

**Comment by gthole** [comment]
Ignoring the `relating` component of this, I've implemented the "clone" piece. In the recipe details, if you open the menu there's an option to "Make a Variation".

This copies the "directions", "description", "quantities", and "tags" into a new recipe form. ("book", "name", "source", and "url" are not copied over).

@jelloeggy If this sounds right, I'll commit and deploy.
