### ISSUE TITLE
new font makes UOM quite small

### ISSUE THREAD

**Issue by jelloeggy** [gthole/drink-stash#14]
OK, perhaps this is more a preference than a bug, but the recently added font changes enhance the amount of an ingredient while minimizing and fading the actual unit of measure, meaning it is easier to make a mistake in amounts. 

![screenshot 2019-03-05 at 9 27 43 pm](https://user-images.githubusercontent.com/45017933/53851792-d0f27500-3f8d-11e9-94c9-b36d1b421040.png)

**Comment by jelloeggy** [comment]
The above screenshot also perhaps does not appropriately show how small it is on the screen. The use of fractions in the current font can also make it very small and easy to mistake. See full screen view:
![screenshot 2019-03-05 at 9 37 41 pm](https://user-images.githubusercontent.com/45017933/53852139-ec11b480-3f8e-11e9-95eb-994f93c0dc9c.png)

**Comment by gthole** [comment]
Yeah, I was worried about this.  I'll modify the font sizes and weights to try to make them clearer.  I like how pretty it is like this, but pretty shouldn't cause measuring mistakes.

I've also considered a user setting to let the user decide if they want to see fractions or decimals.

**Comment by gthole** [comment]
How's this for more readable quantities?
<img width="754" alt="screen shot 2019-03-06 at 7 50 19 pm" src="https://user-images.githubusercontent.com/1581949/53924199-30fa2180-4049-11e9-8930-64fca3f56377.png">

**Comment by jelloeggy** [comment]
Looks good on the phone, will check at home.

I appreciate the effort at beautification.

**Comment by jelloeggy** [comment]
Sizing looks pretty good at first glance, will let you know if UOM level is problematic after repeated use.

**Comment by gthole** [comment]
🎉  Glad it looks better.  Feel free to re-open this if you think it needs more adjustment.  (The real test would be whether it's usable after already having had a couple.)

**Comment by jelloeggy** [comment]
Yes, I intend to test that use case.
