### ISSUE TITLE
Reposition delete button

### ISSUE THREAD

**Issue by jelloeggy** [gthole/drink-stash#15]
This could be complete user error but twice now I have deleted comments I meant to edit because the position of the "Delete" in the Edit comment page is where I would instinctively click to approve (lower right, i.e. where the "Submit new issue" button is in this github comment.

**Comment by gthole** [comment]
Should we swap it with the "Save" button, switching positions?  (Additionally, I can make the "Delete" button outlined red so it's less prominent, and switches to red-background/white-text on hover.)

**Comment by jelloeggy** [comment]
My initial thought is switching positions would be best. It's so infrequently used its hard to say but perhaps worth trying.

**Comment by gthole** [comment]
I'm game.  Though if I'm swapping the positions on the comment edit view, I should swap them on the recipe edit view too, which will mean that on the new recipe view, the "Save and New" button will be on the left now and just "Save" will be on the right, which I think is correct.  Sound right?  (Or was it left?)

**Comment by jelloeggy** [comment]
So I think the "Add new" buttons should be left as is. But yes, in the Edit recipe screen, where you have the possibility of deleting a recipe, they should be swapped. 

Although...if I'm being picky...delete should probably be completely abstracted from an edit screen.

Also- I'm sorry, but I literally walked home tonight thinking about adding Vieux Carre.

**Comment by gthole** [comment]
Button swap deployed.  Maybe another time you can clarify what "completely abstracted" means. `:)`

(Also :brainy:)
