### ISSUE TITLE
Save and Save + New order are reversed in tabbing

### ISSUE THREAD

**Issue by jelloeggy** [gthole/drink-stash#16]
There seems to be a regression with the latest push (I assume related to button position trading) that when tabbing through the "Add new recipe" screen, the first button highlighted after writing the description is "Save and New" on the right, followed by "Save" on the left, switching the intuitive left-to-right tab positioning.

**Comment by jelloeggy** [comment]
(I have learned to work around this by0-p;k-p[=;'';;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,.

**Comment by jelloeggy** [comment]
Ok, Jack's github access has been revoked. I have learned to press tab just once, but probably for general use it should follow the usual flow.

**Comment by gthole** [comment]
Silly Jackbug.

Good catch!  I deployed the fix and also added some on-focus feedback that should clear up which button is shown on tabbing.
