### ISSUE TITLE
Add filtering feature that allows for swiping in mobile

### ISSUE THREAD

**Issue by jelloeggy** [gthole/drink-stash#19]
We should start to think about how people filter down to the drink they want to make, and potentially, to save drinks for later. Our new user suggested swiping, his notes on this topic: 

I really like this as a mobile app, so yeah, anything that can utilize those gestures would be super helpful. For instance, if I search for something on Kindred Cocktails (on desktop) and get 30 recipes back, I will generally open them all in new tabs, then go through and close the tabs I decide against, leaving me with a shorter list I can whittle down. The swiping here would make that super easy -- filter down to a dozen recipes and then swipe away half of them quickly because they contain ingredients I don't like or don't have. You could even build on that gesture later on to swipe left for adding recipes to your own lists (e.g., create a new drinks list like "party drinks" for an upcoming event, then do a recipe search and filter down results, swiping ones you like into your list. Now you have a defined menu you can pull up any time at the party.)

**Comment by gthole** [comment]
I ... really love this idea.  I'd been struggling with the idea of how to incorporate bookmarks into the app without overloading the filtering UI.  Like, I keep seeing recipes that I want to try but don't feel like I'm ready to comment or favorite them.

So if I could have lists of recipes (drinks for a party, favorites, drinks I want to try, drinks my Mom loves, etc.) then it'd be a great way of keeping arbitrary sets of recipes for whatever purpose.

Though now I'm basically building Pinterest for lushes.

**Comment by jelloeggy** [comment]
So...basically laying the groundwork for an insanely successful product?

**Comment by gthole** [comment]
Yeah, though it'll be a lot of work to even figure out how the UX is going to look.  There appear to be some [solid frameworks](https://www.npmjs.com/package/hammerjs) for mobile gestures, so that could be a starting point.

**Comment by jelloeggy** [comment]
Also, how should the desktop version work for actions that are swipe in mobile? an X? Arrows pointing left and right?

**Comment by gthole** [comment]
I haven't really thought it through yet, but my rough thinking was that for list curation on desktops, you'd have the left-panel view to choose from and could drag recipes into the list a la Trello.  Not sure yet how you'd remove them from the left panel (the swipe-left action on mobile).  Plus desktop screens that are narrow should still support an add/remove capability without the side-by-side view.

My head's getting a little fuzzy thinking about it.

**Comment by jelloeggy** [comment]
Well no need to feel fuzzy, you could also research options and it can wait until we can do a proper design session.

**Comment by gthole** [comment]
Well, I'm thinking through data models, since that's a lot easier than the UI parts.

I'm thinking something like:

```
RecipeList
user_id -> User
name -> varchar
description -> varchar
created -> datetime
```

```
RecipeListEntry
list_id -> RecipeList
recipe_id -> Recipe
order -> number
notes -> varchar
```

Then maybe a `Share` object to let users share lists with each other.
I might also try implementing the "swipe left to dismiss" thing from the regular recipe view.

But yes, I definitely want to do a real design session before trying to actually build anything involved.

**Comment by gthole** [comment]
@jelloeggy - So I might have stayed up last night working on "swipe" gestures on the recipe list view.  I have an experimental branch deployed temporarily if you want to give it a try on mobile.  It's definitely not perfect, but I'm curious about what you think.

**Comment by jelloeggy** [comment]
Wow the swipe action is awesome (though hopefully you didn't lose sleep).
It's pretty slick. I assume it is just a "remove from this view" result at
the moment and doesn't actually add to a list somewhere depending on
left/right?

**Comment by gthole** [comment]
Glad it works, and I didn't even lose any sleep over it!  Correct - right now it doesn't do anything besides clear a recipe out of the list.

My thinking is to next add Lists and an "Add to List" button on the recipe details page (which will replace favorites).  I'll implement the rest of "swipe left to ignore" but remove "swipe right" for now, since I think that'll be a more complicated user experience to design.

Do you have any thoughts on lists before I start working into it?

**Comment by jelloeggy** [comment]
Are you thinking that people would create and name their own lists? If so,
I think that sounds great, assuming you can add drinks to more than one
list. And then sharing/swipe to add/etc can come later.

**Comment by gthole** [comment]
Yup - you got it!  Users can each have multiple lists that have a name and description, and each recipe in the list can optionally have a note.

**Comment by gthole** [comment]
OK, I have an early version of user lists working.  It's not hooked up to the swipe gestures yet, so you add/remove recipes from lists on the recipe details view.

There's a lot of cleanup work to do on it (make it prettier, etc), but I'd appreciate a product/QA round when you have the time.

**Comment by jelloeggy** [comment]
Product/QA round 1:
So far, with very limited testing, I haven't found functional issues, but definitely some usability improvements to request.
1) It's difficult to know that the drink has been added to the list. I think that maybe a check box when selecting the list might be clearer than highlighting? This is low priority. Also low priority, a clearer way to exit the "add to a list" workflow than "click on the x" (such as "Save", "Done", etc).
2) More helpful would be a marker on the recipe itself indicating its now on a list, preferably even to see a summary of lists it's part of. Also, it was nice to see drinks that had been favorited by myself or others right from the recipe page and use it as a filter, perhaps the "Favorites" list could be a special list that has similar features. (OK pipe dream, but eventually users could choose an icon to associate with a list and then that icon would show up in the recipe choice view...spitballing here). 
3) The lists themselves are quite hidden. I did find them (in the profile) but ideally lists would be linked from several places (the main page, the recipe section).

**Comment by gthole** [comment]
All good feedback.  I'll take a look at incorporating some of these suggestions this week.  My plan is to add list additions to the Activity Feed and comments the way that Favorites were, and eventually to add a way to filter the recipe list view by a user list like "Favorites", but that search/filter is what I'll need some help on, especially for swipe gesture managing lists.

Keep the review ideas coming!

**Comment by jelloeggy** [comment]
Just playing with it on mobile (totally legitimate work time) and:
1) I just noticed the "notes" you can add to each recipe when you make a
list. Is that mobile only? What's the intended workflow?
2) It would be great to be able to do an initial search (i.e. NOT lime
juice, mezcal), swipe to clear out the list and then save the remaining
recipes as a list (although I suppose a quick "swipe right to list" feature
may capture this).
3) It also would be really helpful to have a total at the top of the recipe
filter that tells you how many recipes were returned. Given how many
recipes we have now it would be good to know how much more filtering you
need to do to get to a usable list, and it's not immediately apparent after
your initial search.

**Comment by gthole** [comment]
1) Notes are on desktop view too (or at least they should be).  The idea is that you might want to jot down some thoughts about a recipe in the context of that list - my use case is that I want to track things that I've made for people and whether they liked it or not, also what variations I might have made for that person that I wouldn't do otherwise.  Does it seem worthwhile to you?

For the rest of these, and the ones above, would you mind opening separate issues for them?  I think it'd be easier for me to track and ask for feedback on individual changes that way.

(_Totally_ legitimate work time.)

**Comment by jelloeggy** [comment]
Ah, I see the notes on desktop now, they just seemed very prominent on mobile (smaller area to fill I suppose). Do the notes only exist in the context of that particular list? I like the idea of being able to make personal notes, but want to understand the context.

Also, noted and accepted about splitting out my myriad thoughts into actual, distinct items. I will do so later tonight; prepare for the grace-git-onslaught (jelloeggy jamboree? hmm).

**Comment by gthole** [comment]
The notes only exist in the context of that particular list.  They won't show up anywhere else.

(A "jameggy jellobee"?  I may have lost the meaning, but it's fun to say out loud.)

**Comment by jelloeggy** [comment]
I love the idea of additional notes so let's leave it as is for now, I'll put another issue/suggestions if I have ideas as I play with it.

Do you want to close this one out now? I've added "List creation options" as a separate item (#29) so that could capture the "swipe to add to list" request. Up to you, I'm sure there is satisfaction in closing these out.

(Oh my goodness there totally needs to be a "jameggy jellobee" drink now. And/or a gif of dancing jelloeggs. I can work on one of those.)

**Comment by gthole** [comment]
Yeah, I think this one has run its course.  Thanks for all the review!  (Even though I'm tempted to leave it open until there's either a "jameggy jellobee" drink or a dancing jelloegg gif.)

**Comment by jelloeggy** [comment]
Well there is a way to deal with that: #31
