### ISSUE TITLE
Favorites not showing proper totals

### ISSUE THREAD

**Issue by jelloeggy** [gthole/drink-stash#21]
See screenshot - both you and I have favorited "Santa Rosella" and yet it only shows 1 heart in the left panel. 

Possibly irrelevant if you are deprecating favorites.

![Screenshot 2019-03-21 at 8 28 20 PM](https://user-images.githubusercontent.com/45017933/54793256-e3b8ab00-4c17-11e9-8821-fe9ffb5dc1ae.png)

**Comment by jelloeggy** [comment]
Interesting though - I favorited Deep Six, and that appropriately shows "1" so it is not that they aren't registering at all.

**Comment by gthole** [comment]
The number count in the recipe list is the number of comments, not the number of favorites.  I've been thinking I should change it from a nondescript grey badge to an SVG of a comment to make it more meaningful.  Favorites are indeed going away (but I think everyone will get a "Favorites" list by default) so hopefully it'll be less confusing.

(The Santa Rosella is still the best.)

**Comment by jelloeggy** [comment]
Ahhh OK, I don't know why I got confused. Let's close as "works as
designed", especially since favorites are going away. Thanks!

**Comment by gthole** [comment]
Yep!  Definitely some design thinking that has to happen for lists going forward, but I'm happy with this not-a-bug.

**Comment by jelloeggy** [comment]
Looking forward to design sessions!
