### ISSUE TITLE
Mobile activity feed not properly refreshing

### ISSUE THREAD

**Issue by jelloeggy** [gthole/drink-stash#22]
Since the last noted activity feed issues (when it wasn't refreshing and you corrected it) I don't think I had verified the feed in mobile - the last feed item showing there for me is Jersey Isle Julep, which was added 11 days ago. Desktop feed seems fine.

I have tried logging in and out, and refreshing. I haven't cleared cache completely, I'm not entirely sure how to do that in mobile, but can if desired.

**Comment by gthole** [comment]
My guess is that it's the browser cache from when I mistakenly told the server to add a year-long "expires" header to every single response.  Basically means that your phone will never update anything that it's already asked for until you clear the cache.  (derf - sorry about that.)

**Comment by jelloeggy** [comment]
Well, I just had to factory reset my phone (for other reasons, derf indeed)
so I'll be able to see if it refreshes going forward. If you think it
should work going forward we can just close this out. Or are you saying
mobile refresh will never work?

**Comment by gthole** [comment]
Oh I see how that could have been read two ways.  It should work going forward.  The "expires" header problem is fixed, and once the cache is cleared it will get the correct headers.  (Factory reset tho?  That's serious.)

**Comment by gthole** [comment]
Is it working OK on your phone?  Can we close this issue out for now?

**Comment by jelloeggy** [comment]
Yup all set. Closing!
