### ISSUE TITLE
Make it clearer that a drink has been added to a list

### ISSUE THREAD

**Issue by jelloeggy** [gthole/drink-stash#24]
It's difficult to know that the drink has been added to a list. I think that maybe a check box when selecting the list might be clearer than highlighting.

**Comment by gthole** [comment]
I pushed a change for this.  You're right - it's so much better this way.
<img width="706" alt="Screen Shot 2019-03-26 at 6 27 05 AM" src="https://user-images.githubusercontent.com/1581949/54990071-3edbfc00-4f90-11e9-9c55-906d1e1e09fe.png">

**Comment by jelloeggy** [comment]
Hooray! Looks good! (though what's the difference between Bookmarked and Favorites?)

**Comment by gthole** [comment]
(Things I'd like to try at some point, but don't necessarily have the stuff or time on hand at the moment.  I keep coming across recipes that I'm like "ooo that looks good - I want to try that one sometime".)

**Comment by jelloeggy** [comment]
(Well, should you decide to replenish, I have been personally given the heads up that the BSFW Grand Digestif tasting will be Tax Day, April 15th).
