### ISSUE TITLE
Show that a recipe has been added to a list on the recipe page

### ISSUE THREAD

**Issue by jelloeggy** [gthole/drink-stash#25]
Show a summary of lists that a recipe has been added to on the recipe page.

**Comment by gthole** [comment]
I'm thinking links to each of the lists that a recipe is a part of and maybe "Create a new list with this recipe".

I tinkered with this a little last night and haven't figured out yet how to do it without it looking awful.  I'll keep at it though, since I think it'll be a nice feature.

**Comment by jelloeggy** [comment]
Just realized you added this here...I just made the same comment on #29.

**Comment by gthole** [comment]
I took a stab at this and deployed it out.

**Comment by jelloeggy** [comment]
This all looks great except that the "create a new list with this drink" link doesn't function.

**Comment by gthole** [comment]
Ah true!  Give it a try now?

**Comment by jelloeggy** [comment]
Thumbs up!
