### ISSUE TITLE
Lists should be more obvious

### ISSUE THREAD

**Issue by jelloeggy** [gthole/drink-stash#28]
The lists themselves are quite hidden. I did find them (in the profile) but ideally lists would be linked from several places (the main page, the recipe section).

**Comment by gthole** [comment]
I added lists to the main page (and moved the "Add recipes" link into the menu, since it's less of a primary action).  I'll add a link to lists to the recipe details page for another issue.

**Comment by jelloeggy** [comment]
I'm not sure I totally agree adding new recipes isn't a primary task (it's certainly one we want to encourage). However I like the new link, and I would gladly accept a clearer "Add New Recipes" from the actual Recipes page in its stead.

**Comment by gthole** [comment]
OK, here's what I'm thinking:

- Move "Liquor Cabinet" off the front page, restore "Add Recipes" in its place.
- Move the "Cabinet" view functionality into the "Profile" view, delete the "Cabinet" view.
- Make the lists in the "Profile" view be just that user's 5 most recent lists.
- Add the cabinet management underneath that (visible only to oneself) in the "Profile" view.
- Add a "Lists" view at `/lists` that shows a user their own lists.
- Add a "Lists" view at `/users/<id>/lists` that shows a user someone else's lists, linked from that user's profile view.

Phew.  Whatcha think?

**Comment by jelloeggy** [comment]
Phew indeed! Thoughts inline below:


   - Move "Liquor Cabinet" off the front page, restore "Add Recipes" in its
   place. <--yup, definitely.
   - Move the "Cabinet" view functionality into the "Profile" view, delete
   the "Cabinet" view.  <--By that you mean the cabinet filter on the recipes
   page? If so, sounds good, I've never used that filter.
   - Make the lists in the "Profile" view be just that user's 5 most recent
   lists. <-- Ah, my question of "how will they see other lists" is answered
   below.
   - Add the cabinet management underneath that (visible only to oneself)
   in the "Profile" view. <-- probably fine, will need to see it
   - Add a "Lists" view at /lists that shows a user their own lists.
   <--super
   - Add a "Lists" view at /users/<id>/lists that shows a user someone
   else's lists, linked from that user's profile view. <--and we'll play with
   permissions on this?

**Comment by gthole** [comment]
`By that you mean the cabinet filter on the recipes page?`
No - the cabinet filter button on recipes list (which I use quite a bit) would stay.  But the functionality of the "/cabinet" view (selecting ingredients) would be moved to the "Profile" view.

`and we'll play with permissions on this?`
Yep!  But later.  Right now everything is visible to everybody, but users can only modify their own stuff.  If/when we start taking on more users we'll want to sort out what the permission/visibility settings of everything is.  Future discussions.

**Comment by jelloeggy** [comment]
Ah ok, I thought you had mentioned that in a prior item but basically
thumbs up, it all sounds good.

**Comment by gthole** [comment]
OK, I did this, but a little bit differently.

- Lists are now at `/users/<username>/lists`
- Liquor cabinet management is at `/users/<username>/cabinet`

There are a number of other minor changes I have planned, but I like this as a basic structure now.

**Comment by jelloeggy** [comment]
Nice! Once we figure out the sharing of lists (besides just editing the
url, which is still nice to have) we could have a suggest feature to
suggest items for other people's lists.

However, now that I've poked at lists - edit is broken. I'll enter a
separate bug.

**Comment by gthole** [comment]
Yep.  I think there are some good user interactions to sort out once we start thinking through relationships between users generally (like "Following" and what objects have visibility/privacy settings etc.)

**Comment by gthole** [comment]
Whatcha think - can this one be closed out?

**Comment by jelloeggy** [comment]
Yup, well done sir.
