### ISSUE TITLE
Provide better error handling when adding recipes

### ISSUE THREAD

**Issue by jelloeggy** [gthole/drink-stash#34]
Specifically I am thinking about when adding a recipe where the name already exists, making it clear that is the case, rather than just throwing a generic error. Ideally, it might even recognize the dupe before you've entered the whole recipe!

Also, I am getting an error when trying to enter something that is listed as "1/6". Any version of .1666... that I enter gets an error, i'm assuming because of the conversion to fractions. However, I just get a generic error.

All low priority, clearly!

**Comment by gthole** [comment]
Good call - I've deployed a fix that checks the name and supports fractions in the recipe new/edit view.

Want to give it a QA round and report back?

**Comment by jelloeggy** [comment]
Name check looks great!! Fractional funciton seems to work, don't know if it behaves strangely on the back end (I added "Starbird" if you want to look). I think I'd call this a close.
