### ISSUE TITLE
Add a way to remove recipes from lists.

### ISSUE THREAD

**Issue by jelloeggy** [gthole/drink-stash#35]
Unless I'm missing something, I can't remove a recipe from a list.

**Comment by gthole** [comment]
You can remove them by un-checking them in the "Add to Lists" modal on the recipe details view, but I've been thinking that I should add a "remove" or "X" button somewhere on the list details view.

**Comment by jelloeggy** [comment]
Ahhh yes, of course. Yes, I think a quick edit from list details would make sense, either an x/remove per recipe or a selection box to select several and delete. Actually now that I think about it building a selection box with "Delete all selected" might lead to other "select then action" functionality. For instance, if you have a long list of Favorites or Someday drinks, select several and "Move to new lists" or "Clone to new list". What do you think?

**Comment by gthole** [comment]
OK, deployed an "X" to remove recipes from a list on the list details view.  QA round at your convenience!

**Comment by gthole** [comment]
Whoop, just saw your other comment.

Yes, I like that idea a lot, but would put it on the back burner for future features.

**Comment by jelloeggy** [comment]
X functionality, er, functional! I assume you want to close this one - do you want me to open a new ticket for the list manipulation functionality or just keep it mind for when the list functionality is more mature?

**Comment by gthole** [comment]
Open a new ticket so we can keep track of it, otherwise later I'll be like "what was that thing".

Drop in all your ideas of possible actions.  Thanks!

**Comment by jelloeggy** [comment]
I would never say that :grawesome:
Opening a "List Management" ticket now.
