### ISSUE TITLE
Adding to lists no longer works

### ISSUE THREAD

**Issue by jelloeggy** [gthole/drink-stash#38]
I tried to add "Ab Fab" to my Favorites and also to "Wanna Try That" and got a "That doesn't look right" error, and the drink did not add. I assume this is related to the Books rollout.

**Comment by gthole** [comment]
Yep!  I can reproduce this when I try to favorite your "Peony" drink.  I'll dig in and see what's up.

**Comment by gthole** [comment]
[Fixed!](https://github.com/gthole/drink-stash/commit/a54197ab2c262372a15092958cac9dca47d5f5fd) (Though I definitely should add unit tests for it.)

**Comment by gthole** [comment]
Tests are added too!
