### ISSUE TITLE
Adding recipes gets an error

### ISSUE THREAD

**Issue by jelloeggy** [gthole/drink-stash#39]
Adding a recipe is now throwing an error, probably due to blocks.

**Comment by jelloeggy** [comment]
![Screenshot 2019-07-22 at 8 45 35 PM](https://user-images.githubusercontent.com/45017933/61674467-f6c0b200-acc1-11e9-9a9b-90dce59996d8.png)

**Comment by gthole** [comment]
Can you shift-reload your browser?  It looks like you don't have the latest web app.

**Comment by gthole** [comment]
Closing as out-of-date browser issue.

**Comment by jelloeggy** [comment]
Yes, sorry I haven't checked it but have confirmed it works on other
browsers.
