### ISSUE TITLE
Adding a book created a duplicate

### ISSUE THREAD

**Issue by jelloeggy** [gthole/drink-stash#40]
I tried to add a new book - Beta Cocktails. I wanted it to be private so did not click the "Public" button but got two books created (26 and 27)

**Comment by gthole** [comment]
OK, I think I know how this happened.  If you press the "Save" button twice in the admin panel, then it performs the action twice.  I can probably drop some javascript code into that admin panel to disable the button after the first click.

**Comment by gthole** [comment]
Fixed!  Please give it a try and see if you can still reproduce this, and close if not.

**Comment by gthole** [comment]
Closing!
