### ISSUE TITLE
Feature request: Provisioning via HTML interface instead of CLI

### ISSUE THREAD

**Issue by SquareBottle** [gthole/drink-stash#45]
Drink Stash sounds like exactly what I'm looking for, but the _very last part_ of the setup process—the provisioning step—is blocking me. I feel so teased!

See, I use a Synology DS218+ as my home server, and it comes with a (mostly) convenient app to manage Docker. It's great for finding, downloading, deploying, and managing containers. This is a convenience for seasoned Docker pros, but it also makes the world of Docker apps more accessible to people for whom it would otherwise be just a bit too complicated—or at the very least, it spares them from however many hours of headaches it might take for them to teach themself. It's pretty great.

However, I can't figure out how to pass CLI commands to the containers. This usually isn't an issue, but that's how the Drink Stash provisioning is done. I've technically got Drink Stash installed, but I'm unable to create any users.

With other apps I've set up, what I do is install the container, use my browser to connect to my DS218+ using whichever port I configured for the app, and then I'm greeted by the app telling me that I need to make the first user. This works great, so if you are considering requests, I'd really appreciate it if you made a way to do the initial provisioning like this.

Thank you for reading.

P.S. I just noticed that you're looking for design help. I'm an interaction designer finishing my master's thesis. I need to make a new portfolio because [my current portfolio is absolutely ancient](https://www.jameslaslavic.com). I made it during my junior year of undergrad, which was quite some time ago. So, I want to do some new projects to show what I've learned since then (here's a PDF of [my current resumé](https://drive.google.com/file/d/18fiCOxkLazJPxJYl00bMOGjw-wqWGr9Z/view?usp=sharing) so you can at least get an idea). Maybe we can help each other?

**Comment by gthole** [comment]
Hi James,
I'm so glad you're interested in Drink Stash. This has been a labor of love for me, but the UI definitely could use some design attention. I'll send you an email to discuss.

To support your Synology use case I made it so you can provision using environment variables on your docker container. See the [updated README](https://github.com/gthole/drink-stash/blob/master/README.md) on the repo. Hopefully this helps you get things going a little more easily.

Best,
Greg
