### ISSUE TITLE
Suggestion- Improve tag interface

### ISSUE THREAD

**Issue by jelloeggy** [gthole/drink-stash#48]
In the edit drink view:
Currently if you enter a tag that doesn't exist you can save but it doesn't actually save, and also doesn't let you know that the reason is because that tag doesn't exist. This is confusing to the user, and the free text field leads you to think you can enter whatever you want there.

This is low priority.

**Comment by gthole** [comment]
I made some adjustments to make it a bit more like the existing app. Try it out now to see if it feels better.

**Comment by jelloeggy** [comment]
Yup, at least feels consistent now.
