### ISSUE TITLE
Adding new books does not add them to the add recipes list

### ISSUE THREAD

**Issue by jelloeggy** [gthole/drink-stash#50]
I added two new books, Three Ingredient Cocktails and Smuggler's Cove, and they aren't showing up in the add recipe view.

Also, I thought you used to be able to add new books right from the Add Recipes view...I don't think only admins should be able to add new books as it discourages other people adding recipes.

**Comment by gthole** [comment]
Books are cached in the browser to reduce the request overhead. Reloading the browser, or potentially opening a new tab, should make the book available in the UI.

Books were never create-able by non-staff. Book management is definitely something to add, but please open a new feature request issue for that.

**Comment by jelloeggy** [comment]
I've refreshed the browser several times and opened a new incognito browser and they didn't show up. However I am just realizing that although I explicitly added you as an editor, I didn't add myself (I assumed my creation of the book would make me an editor). Let me see if that is it.

**Comment by jelloeggy** [comment]
Yup. That was it. I'll close this and if others not being able to add books becomes an issue for them I can add a feature request.
