### ISSUE TITLE
Books and Source are redundant

### ISSUE THREAD

**Issue by jelloeggy** [gthole/drink-stash#51]
When adding new recipes you must choose a book, but if that book is also a source then you have to enter the book again as a the source. This makes sense when it is not an actual Book (like book = Grace Public/source = Grace + Date) but maybe the book name could auto populate in the source, but with the ability to overwrite it?

**Comment by jelloeggy** [comment]
Huh...I think this exists as requested if you do "Save and Add Another" but not for the first drink you enter. The source is now autopopulating...

**Comment by gthole** [comment]
Note that `source` is not a required field. I should go through and add helper text to all the fields in the Recipe Add/Edit view. The auto-populate thing is that if you add a recipe and press "Save and New" then it keeps the `book` and the `source` from the previous recipe so you don't have to keep re-entering them.

I also may change the title of that field to "Source Notes".

**Comment by gthole** [comment]
Pushed an update for this. Please take a look at the subtext on the recipe edit/new page and close this or suggest changes.

**Comment by jelloeggy** [comment]
Do you plan on displaying the Book in the Recipe View? If not it might be worth noting that the Book will not be displayed but the Source will.

**Comment by gthole** [comment]
Resolved!
