### ISSUE TITLE
Feature Request: Lists showing in recipe view

### ISSUE THREAD

**Issue by jelloeggy** [gthole/drink-stash#53]
Feature request from Lillian: ability to see which of my lists (if any) a drink is in when I’m browsing recipes (so I can know if a drink is already added to one of my “want to try” lists without having to click in)

**Comment by gthole** [comment]
Like, in the recipe list?

**Comment by jelloeggy** [comment]
Yes I imagine maybe a label like we have the tags?

**Comment by gthole** [comment]
I think we can close this one now, since we do bookmarking and comment icon filling. Reopen if otherwise!
