### ISSUE TITLE
Conversion Math incorrect for oz to cups

### ISSUE THREAD

**Issue by jelloeggy** [gthole/drink-stash#54]
The app seems to be using a conversion of 4oz = 1 cup (see screenshots)

![Image from iOS (2)](https://user-images.githubusercontent.com/45017933/88390873-1da73d80-cd87-11ea-802e-2dda4c47a0db.png)
![Image from iOS (1)](https://user-images.githubusercontent.com/45017933/88390875-1e3fd400-cd87-11ea-8013-8a0a611af648.png)

**Comment by gthole** [comment]
Fixed!

**Comment by gthole** [comment]
Also NB: I've added a UOM of "can".
