### ISSUE TITLE
"Uh-oh. This resource wasn't found" error

### ISSUE THREAD

**Issue by DDAYAM** [gthole/drink-stash#78]
I hit this error whenever I attempt to navigate to the following:
1. Manage Your Liquor Cabinet
2. Build Lists
3. My Profile
4. Edit Profile

<img width="1412" alt="Screen Shot 2021-12-17 at 3 15 21 PM" src="https://user-images.githubusercontent.com/26150528/146602905-04ea4721-3910-426b-ad08-a4c6ef505b9f.png">

**Comment by gthole** [comment]
What's the path that it's directing you to? It sounds like the browser app isn't able to find your user by the username in the path. That username is taken from the JSON web token received via login, so there seems to be a disconnect between the auth token and the api call for the user details.

**Comment by DDAYAM** [comment]
https://drinkstash.app/users/Andrew.mcdowell/cabinet is the path that, I believe, jives with my user.

**Comment by gthole** [comment]
All fixed! Give it a look over and if something still doesn't work correctly, please reopen this issue. Thanks for the report!
